Anselmoo/spectrafit

.pre-commit-config.yaml
README.md

Link to synopsis

---

docs/interface/features.md
spectrafit/spectrafit.py

Automatic adding of user name and system for the meta data for fixing issue: #51

Fixing issue #51: Add auto user name and system

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

Updating packages for small release

Updating packages for small release

---

.github/workflows/python-ci.yml
poetry.lock

Update poetry.lock and python-ci

---

.github/workflows/python-ci.yml

Allow pre-commit creating PRs

---

spectrafit/models.py

See: [https://en.wikipedia.org/wiki/Voigt_profile#Pseudo-Voigt_approximation](https://en.wikipedia.org/wiki/Voigt_profile#Pseudo-Voigt_approximation)

Correct  Pseudo-Voigt power factor from 0.25 to 0.2

---

.github/workflows/python-ci.yml
.gitignore
CONTRIBUTING.md
poetry.toml

Update .gitignore and pre-define prettier-ci

Adding prettier to the CI pipeline

---

.github/workflows/python-ci.yml
.prettierignore
CHANGELOG.md
SECURITY.md
docs/doc/fitting.md
docs/examples/example4.md
docs/examples/example7.md
docs/interface/features.md
docs/interface/usage.md

Add prettier into the CI for checking: 
1. `JSON` 
2. `MD`
3. `YAML`
4. `YML`

Add prettier in the CI-workflow

---

docs/doc/models.md
pyproject.toml
spectrafit/__init__.py
spectrafit/models.py
spectrafit/spectrafit.py
spectrafit/test/test_input.py
spectrafit/test/test_models.py
spectrafit/test/test_tools.py
spectrafit/tools.py

Update raise back
Bump from 0.8.0 to 0.8.1

Updating all raises

---

CHANGELOG.md
poetry.lock
pyproject.toml
spectrafit/__init__.py

Bump spectrafit from 0.8.3 to 0.8.4

---

CHANGELOG.md
pyproject.toml
spectrafit/__init__.py

Update for release

---

Dockerfile

---
update/change?
#328
---
---

Fixed -> [Bug]: Docker Image cannot be build #328

---

.devcontainer/devcontainer.json
.github/ISSUE_TEMPLATE/codespace_feature_request_form.yaml
.github/ISSUE_TEMPLATE/documentation_request_form.yaml
.github/release-drafter.yml
.github/workflows/python-ci.yml

---
Fixed #332 
update/change?
---
---

Fixed #332 ->  Issue Template for CodeSpaces

---

pyproject.toml
spectrafit/__init__.py

build: :bricks: Update version to 0.10.0

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :pushpin: Add numdifftools = "^0.9.39"

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

---
- x ] Have you checked to ensure there aren't other open
update/change?
---
---

fix: :arrow_down: Downgrade openpyxl

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

Add missing dependecies for installer
---
update/change?
---
---

fix: :bug: Add tqdm PyYaml

---

.devcontainer/devcontainer.json
INSTALLATION.md
README.md
pyproject.toml
spectrafit/__init__.py

docs: 📝 Add docs about conda forge

---

.devcontainer/devcontainer.json
.github/release-drafter.yml
CHANGELOG.md

ci: :wrench: Update devcontainer and release drafter for codespace

---

.gitmodules
LICENSE

Modified license and add vendor folder for `report.py`
---
update/change?
---
---

docs: :page_facing_up: Modified license and add vendor folder

---

.sonarcloud.properties

Add .sonarcloud.properties for handling and checking code quality
---
update/change?
---
---

feat: :recycle: Add .sonarcloud.properties

---

CHANGELOG.md
docs/doc/statistics.md
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/models.py
spectrafit/report.py
spectrafit/spectrafit.py
spectrafit/test/test_input.py
spectrafit/test/test_tools.py
spectrafit/tools.py

feat: :bulb: Add advanced metric for R2 statistic

---

.devcontainer/devcontainer.json
.github/workflows/python-ci.yml
.github/workflows/release.yml

fix: :fire: Add -E jupyter to create docs

---

.devcontainer/devcontainer.json
.devcontainer/setup.sh
.github/workflows/python-ci.yml
.github/workflows/release.yml

fix: :bug:  Updating devcontainer setup

---

poetry.lock
pyproject.toml
spectrafit/plugins/converter.py
spectrafit/plugins/test/test_converter.py
spectrafit/tools.py

feat: :building_construction: Change from `toml` to `tomli`

---

.devcontainer/setup.sh
.github/workflows/devcontainer.yaml
CHANGELOG.md
INSTALLATION.md
SECURITY.md

feat: 🏗️ Add ci test for devcontainer

---

.github/workflows/devcontainer.yml
.github/workflows/python-ci.yml

feat: :fire: Updating ci for devcontainer

---

.pre-commit-config.yaml

add: ♻️ prettier to pre-commit

---

.github/workflows/codeql-analysis.yml
.github/workflows/devcontainer-ci.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml

refactor: :recycle: CI workflows

---

.github/workflows/python-ci.yml
sonar-scanner.properties

fix: :construction_worker: Add Windows Image back

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
spectrafit/api/cmd_model.py
spectrafit/api/models_model.py
spectrafit/api/notebook_model.py
spectrafit/api/tools_model.py
spectrafit/app/test/test_app.py
spectrafit/plugins/notebook.py
spectrafit/tools.py

ci: :sparkles: Add pyupgrade

---

.devcontainer/setup.sh
.github/labeler.yml
.github/workflows/python-ci.yml
.pre-commit-config.yaml
INSTALLATION.md
README.md
docs/plugins/jupyter-spectrafit-interface.md
mkdocs.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/plugins/notebook.py
spectrafit/plugins/test/test_notebook.py

test: ⚡ add missing test for coverage

---

.devcontainer/setup.sh
.github/workflows/python-ci.yml
CHANGELOG.md
pyproject.toml
spectrafit/__init__.py

fix: :ambulance: devcontainer

---

.github/workflows/docker-ci.yml
.github/workflows/python-ci.yml
Dockerfile
poetry.lock
pyproject.toml
spectrafit/__init__.py

feat: 🐳 Update docker-image

---

.github/workflows/docker-ci.yml

feat: 🐳 Update docker-image (#462)

---

.github/labeler.yml
pyproject.toml
spectrafit/__init__.py

chore: :bookmark: v0.12.3

---

.github/workflows/python-ci.yml
.github/workflows/release-cd.yml
CHANGELOG.md
docs/license.md

style: :memo: Update Changelog and LICENSE in docs

---

CHANGELOG.md
Dockerfile
pyproject.toml
spectrafit/__init__.py

fix: 🐛 dependencies in pyproject and docker file

---

.imgbotconfig 

feat: :bricks: Add imgboot config

---

CHANGELOG.md
Dockerfile
pyproject.toml
spectrafit/__init__.py

feat: :zap: Change `spectrafit` to `spectrafit-all`

---

CHANGELOG.md

docs: :memo: Add images to Jupyter-Notebook for linking

---

INSTALLATION.md

docs: :memo: Add img example

---

spectrafit/app/app.py
spectrafit/models.py
spectrafit/plugins/converter.py
spectrafit/plugins/notebook.py
spectrafit/plugins/test/test_converter.py
spectrafit/report.py
spectrafit/spectrafit.py
spectrafit/test/test_tools.py
spectrafit/tools.py
spectrafit/utilities/transformer.py

feat: :recycle: Refactor code via Copilot

---

.github/workflows/dependency-review.yml

feat: :construction_worker: Add 'Dependency Review'

---

.github/workflows/gitlab-mirror.yml

feat: :construction_worker: Add gitlab mirroring

---

spectrafit/report.py
spectrafit/test/test_report.py

fix: :white_check_mark: Increase coverage

---

spectrafit/plugins/test/test_notebook.py
spectrafit/utilities/test/test_transformer.py

ci: :white_check_mark: Increase coverage

---

.devcontainer/devcontainer.json

fix: :bug: Deactivate Fish

---

.devcontainer/devcontainer.json
spectrafit/report.py

---
update/change?
---
- Fixed: #507 
- Fixed: #417 
---

fix: 🏗️ Update devcontainer

---

pyproject.toml
spectrafit/__init__.py

fix: :ambulance: Fixed version backwards

---

spectrafit/report.py

fix: :ambulance: Introduce `try-except` for RegressionMetrics

---

pyproject.toml
spectrafit/__init__.py
spectrafit/plugins/notebook.py
spectrafit/plugins/test/test_notebook.py
spectrafit/report.py

feat: :zap: Add optional output for peaks

---

CHANGELOG.md
INSTALLATION.md
README.md

docs: :memo: Add further explenation for conda installation

---

.pre-commit-config.yaml
spectrafit/plugins/test/test_converter.py
spectrafit/plugins/test/test_notebook.py
spectrafit/report.py
spectrafit/test/test_tools.py
spectrafit/tools.py

test: ♻️ partially refactor of test

---

.github/labeler.yml

fix: :construction_worker: Typo in labeler

---

.github/workflows/python-ci.yml
.pre-commit-config.yaml
INSTALLATION.md
SECURITY.md
docs/api/converter_api.md
docs/plugins/data-converter.md
docs/plugins/spectrafit-file-converter.md
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/plugins/converter.py
spectrafit/plugins/data_converter.py
spectrafit/plugins/file_converter.py
spectrafit/plugins/pkl_converter.py
spectrafit/plugins/pkl_visualizer.py
spectrafit/plugins/test/test_converter.py
spectrafit/report.py
spectrafit/test/test_report.py
spectrafit/test/test_tools.py
spectrafit/tools.py

Add a pkl file converter and visualizer for RIXS data
---
update/change?
---
---

feat: :zap: Add pkl file converter and visualizer

---

.pylintrc
pyproject.toml
spectrafit/plugins/pkl_converter.py
spectrafit/plugins/pkl_visualizer.py
spectrafit/plugins/test/test_converter.py
spectrafit/test/test_tools.py
spectrafit/tools.py

feat: 💾 improve `pathlib` handling

---

.pylintrc
spectrafit/plugins/notebook.py
spectrafit/report.py
spectrafit/spectrafit.py
spectrafit/test/test_report.py
spectrafit/utilities/test/test_transformer.py

fix: :test_tube: `# pragma: no cover` for while routine

---

spectrafit/report.py

fix: :rotating_light: `Pylint` Fix

---

spectrafit/test/test_report.py

fix: :arrow_up: Coverage rate

---

.github/workflows/devcontainer-ci.yml
.github/workflows/python-ci.yml
.github/workflows/release-cd.yml
poetry.lock
pyproject.toml
spectrafit/__init__.py

test: ⚡ improve CD workflow

---

spectrafit/test/test_report.py

fix: :ambulance: Change from `property` to `method`

---

.pre-commit-config.yaml

fix: :heavy_minus_sign: Deactivate temp. `pylint`

---

docs/plugins/pkl-converter_visualization.md

docs: :recycle: Refactor layout docs

---

.pylintrc
Examples/example_5_summary.json
Examples/example_6_summary.json
Examples/example_7_summary.json
Examples/example_8_summary.json
Examples/example_8_summary.lock
docs/interface/features.md
docs/plugins/file-converter.md
docs/plugins/jupyter-interface.md
spectrafit/api/cmd_model.py

style: ✏️ Change user_system to host_info

---

docs/examples/example9_6.ipynb
spectrafit/models.py

fix: :bug: Correct typo in `args_minimizer`

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :bookmark: Bump to `0.15.1`

---

.github/workflows/devcontainer-ci.yml

ci: :wrench: Reactivate devcontainer

---

README.md

Change from container to GitHub repo to see the all SpectraFit packages and subpackages.
---
update/change?
---
---

doc: ✏️ change to GitHub repo

---

.github/workflows/python-ci.yml
.github/workflows/release-cd.yml
spectrafit/report.py

fix: 🧹Reorder type of report print

---

docs/doc/models.md
spectrafit/models.py
spectrafit/test/test_models.py

fix: :recycle: Rewrite notation for cumulative functions

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml

feat: :package: Add `poetry` definition for `pre-commit`

---

poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/tools.py

fix: :recycle: Removed `print`

---

poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/api/models_model.py
spectrafit/models.py

Fixes #603
---
update/change?
---
---

feat: :zap: Using the distribution API

---

.github/labeler.yml
.github/release-drafter.yml

Fixes #657
---
update/change?
---
---

docs: :bookmark: Extend release drafter

---

.github/release-drafter.yml

docs: 🧹 Update release-drafter.yml

---

.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

Change activation of auto writing `changelog` by modifying `types`.
Fixes #657
---
update/change?
---
---

fix: :bookmark: Change activation of auto writing changelog

---

CHANGELOG.md
pyproject.toml
spectrafit/__init__.py

fix: :green_heart: Update auto change log release

---

.github/workflows/python-ci.yml

Update python-ci.yml via `--rebase` to allow for building versioned GitHub-pages.
Fixes #662
---
update/change?
---
---

fix: 🔧 Update python-ci.yml

---

.github/workflows/python-ci.yml

fix: 🔧 force push for deploy

---

.github/workflows/python-ci.yml

fix: :memo: Update deploy name

---

mkdocs.yml

docs: 📔 Update mkdocs.yml

---

.github/workflows/update-changelog.yaml

ci: 🔒 update-changelog.yaml

---

.github/workflows/python-ci.yml

ci: ⏮️ removed `--force`

---

.github/workflows/python-ci.yml
.github/workflows/update-changelog.yaml

Fixes #673
---
update/change?
---
---

fix: :memo: Avoid double creating docs in `main`

---

.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

ci: 🚚 Update update-changelog.yaml

---

.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

Fixes: 
---
update/change?
---
---

fix: :green_heart: Update `deps` and `CD`

---

.github/workflows/release-cd.yml
.github/workflows/update-changelog.yaml
pyproject.toml
spectrafit/__init__.py

fix: :memo: Update docs by `mike`

---

.github/workflows/release-cd.yml

ci: 🔧 release-cd.yml

---

.github/workflows/release-cd.yml
.github/workflows/update-changelog.yaml

docs: :green_heart: Docs building

---

.github/workflows/update-changelog.yaml

fix: :bug: Update settings for creating branch

---

.github/workflows/update-changelog.yaml

ci: 📖 Update update-changelog.yaml

---

.github/labeler.yml
.github/release-drafter.yml
poetry.lock
pyproject.toml
spectrafit/__init__.py

docs: :green_heart: Update labeled criteria for `CHANGELOG`

---

.github/labeler.yml
poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :bookmark: Start with beta release

---

.github/labeler.yml
.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

fix: :green_heart: Fix changelogger

---

.github/labeler.yml
.github/workflows/update-changelog.yaml
pyproject.toml
spectrafit/__init__.py

Removed `ASCII` Char in creating branch  by using `released_tag`
Fixes #700
---
update/change?
---
---

fix: :construction_worker: Change from `release_name` to `release_tag`

---

.github/labeler.yml

Change from `CONTRIBUTING.md` to `CHANGELOG.md`
---
update/change?
---
---

fix: 📃 Update labeler.yml

---

.github/release-drafter.yml

chore: :arrow_up: Vendor Packages

---

docs/examples/example9_4.ipynb
poetry.lock
pyproject.toml
spectrafit/__init__.py

docs: :memo: Improve RIXS map example

---

.github/labeler.yml
.github/workflows/python-ci.yml
.github/workflows/update-changelog.yaml
pyproject.toml
spectrafit/__init__.py
spectrafit/api/cmd_model.py
spectrafit/api/test/test_cmd_model.py

feat: ⚡ Improve meta-data handling in report

---

.github/labeler.yml
spectrafit/api/report_model.py
spectrafit/plugins/notebook.py
spectrafit/plugins/test/test_notebook.py

fix: :bug: Allow using solver settings in notebook module

---

.github/labeler.yml
spectrafit/plugins/notebook.py

feat: :wrench: Increase the image resolution

---

CHANGELOG.md

[doc]: 📝 Update CHANGELOG

---

.github/labeler.yml
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/plugins/notebook.py

fix: :bug: Allow return of `dtale` dataframe

---

docs/interface/features.md

docs: :rewind: Apply back `Overall Correlation Analysis`

---

.pre-commit-config.yaml

ci: ➕  Update .pre-commit-config.yaml

---

sonar-scanner.properties

ci: ::arrow_up: Update sonar-scanner.properties

---

.github/workflows/codeql.yml

ci: :zap: Create codeql.yml

---

.devcontainer/devcontainer.json

perf: :arrow_up: Update `devcontainer.json`

---

.devcontainer/Dockerfile
Dockerfile
poetry.lock
pyproject.toml
spectrafit/__init__.py

0.18.3-release

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :bookmark: Minor dependency updates

---

.github/workflows/python-ci.yml
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/models.py
spectrafit/test/test_models.py

feat: :sparkles: added 2. and 3. order polynomial model

---

CHANGELOG.md
spectrafit/models.py

fix: ✍️  Add missing CHANGELOG of `0.18.1`

---

spectrafit/tools.py

chore: :speech_balloon: Change from `errors` to `components`

---

.github/workflows/update-changelog.yaml

- Add [workflow-dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) to check if the updated workflow works
- Add  Auto PR-Request for Release changes
- Cleanup docs for `minor` releases Fixes: #861
---
update/change?
---
---

ci: :building_construction: Update Doc-Release

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :bookmark: v0.20.0

---

.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

fix: 🏗️ Fix building docs and changelog 

---

.github/workflows/update-changelog.yaml

fix: :rotating_light: Update update-changelog.yaml

---

tools/spectra_generator.py

fix: :memo: Update spectra_generator.py

---

SECURITY.md

docs: :memo: Update SECURITY.md

---

.github/workflows/update-changelog.yaml

fix: :construction_worker: try new pr-auto

---

spectrafit/api/models_model.py
spectrafit/api/test/test_models_model.py
spectrafit/test/test_models.py

fix: :bug: Add polynomial-functions to  `ModelsAPI`

---

docs/plugins/pptx_converter.md
mkdocs.yml

Update mkdocs.yml
---
update/change?
---
---

doc: :memo: Add edit buttons to homepage

---

.github/workflows/update-changelog.yaml

ci: :construction_worker: Update `create-pull-request`

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :bookmark: v0.22.0

---

.github/workflows/docker-ci.yml

ci: :test_tube: Testing of Multi-Dockerimages

---

.github/workflows/release-cd.yml

ci: :toolbox: Update docker build

---

.gitattributes
.github/workflows/release-cd.yml
poetry.lock
pyproject.toml
spectrafit/__init__.py

build: ✨  Introducing ARM64 support

---

.github/workflows/release-cd.yml
.github/workflows/update-changelog.yaml
.pre-commit-config.yaml
CHANGELOG.md
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/test/test_models.py
spectrafit/test/test_tools.py

docs: :card_index_dividers: Update CHANGELOG for release/v0.22.1

---

.github/workflows/release-cd.yml

ci: 👷 Change to a different registry

---

.github/workflows/docker-ci.yml
.github/workflows/release-cd.yml

feat: :construction_worker: Using `docker-ci` as workflow for publishing

---

.github/workflows/docker-ci.yml

fix: :pencil:  Add outputs

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/docker-cd.yml
.github/workflows/docker-ci.yml
Dockerfile
INSTALLATION.md

build: :pushpin: Update dependencies

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/api/pptx_model.py
spectrafit/api/test/test_cmd_model.py
spectrafit/models.py
spectrafit/plotting.py
spectrafit/plugins/notebook.py
spectrafit/plugins/rixs_converter.py
spectrafit/plugins/rixs_visualizer.py
spectrafit/plugins/test/test_converter.py
spectrafit/spectrafit.py

fix: :bug: Correct path to logo

---

.github/workflows/devcontainer-ci.yml
.github/workflows/docker-cd.yml
poetry.lock
spectrafit/plugins/test/test_converter.py

build: ⬆️  Update dependencies & tests

---

.github/workflows/python-ci.yml
.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

build: ⬆️ `v0.22.5`

---

.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/docker-cd.yml
.github/workflows/greetings.yml
.github/workflows/labeler.yml
.github/workflows/pylint.yml
.github/workflows/update-changelog.yaml

ci: ♻️  Update linting CI files

---

docs/assets/css/custom.css

revert: :lipstick: Switch back to previous definitions

---

.github/workflows/update-changelog.yaml
CHANGELOG.md

docs: 📝 `Release/v0.22.6`

---

docs/assets/css/custom.css

Update the color scheme according to material design conventions. See also: https://github.com/mbitson/mcg
---
update/change?
---
---

style: :lipstick: Update the color scheme

---

.github/workflows/update-changelog.yaml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

ci: 👷 Add `gh` workflow for auto-release

---

CHANGELOG.md

docs: :card_index_dividers: Update CHANGELOG for release/v0.22.7

---

.github/workflows/update-changelog.yaml
poetry.lock
pyproject.toml
spectrafit/__init__.py

fix: :construction_worker: Update `ci` workflow for auto-release

---

CHANGELOG.md

docs: :card_index_dividers: Update CHANGELOG for release/v0.22.8

---

.github/workflows/update-changelog.yaml

ci: :bug: Add `--push` to apply the delete

---

poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/plotting.py

build: 🏷️ `v0.22.9`

---

CHANGELOG.md

This is an auto-generated pull request to merge release/v0.22.9 with [Changelog](CHANGELOG.md) updates to main.

docs: :card_index_dividers: Changlog update for v0.22.9

---

spectrafit/api/test/test_notebook_model.py
spectrafit/api/test/test_pptx_model.py
spectrafit/test/test_models.py
spectrafit/test/test_report.py

refactor: :recycle: Apply `isclose` for refactoring

---

SECURITY.md

chore: :lock: Update security policy

---

poetry.lock
pyproject.toml
spectrafit/__init__.py

build: :bookmark: Release of `v1.0.0`

---

CHANGELOG.md

This is an auto-generated pull request to merge release/v1.0.0 with [Changelog](CHANGELOG.md) updates to main.

docs: :card_index_dividers: Changlog update for v1.0.0

---

.github/workflows/docker-cd.yml
.github/workflows/greetings.yml
.github/workflows/python-ci.yml
.github/workflows/release-cd.yml
.github/workflows/update-changelog.yaml
spectrafit/__init__.py
spectrafit/plotting.py

perf: :rotating_light: Rebuild fond by `findfont`-method

---

spectrafit/api/pptx_model.py
spectrafit/api/test/test_cmd_model.py
spectrafit/plugins/notebook.py
spectrafit/test/test_models.py
spectrafit/test/test_report.py
spectrafit/test/test_tools.py
tools/spectra_generator.py

refactor: 💡 Add sonartypes recommendations

---

Dockerfile
spectrafit/plugins/data_converter.py
spectrafit/plugins/notebook.py
spectrafit/report.py
spectrafit/test/scripts/test_input_1.json
spectrafit/test/test_tools.py
spectrafit/tools.py
tools/conda_env.fish
tools/conda_env.zsh

feat: ✨ Introduce `min_rel` for confidence integrals

---

pyproject.toml
spectrafit/__init__.py

chore: :bookmark: Update dependencies and version number

---

poetry.lock
pyproject.toml
spectrafit/report.py
spectrafit/test/test_report.py

feat: :sparkles: Add test cases for FitReport class

---

spectrafit/report.py

fix: :seedling: Reorganize report generation in report.py

---

CHANGELOG.md

docs: :card_index_dividers: Update CHANGELOG for release/v1.0.0.post0

---

poetry.lock
pyproject.toml
spectrafit/__init__.py
spectrafit/report.py

fix: :bug: add missing `100%x` in FitReport class

---

CHANGELOG.md

docs: :card_index_dividers: Update CHANGELOG for release/v1.0.0.post1

---

LICENSE

chore: :page_facing_up: Updating to current year

---

.pre-commit-config.yaml

fix: :test_tube: Remove no-commit-to-branch hook from pre-commit-config.yaml

---

.devcontainer/setup.sh

revert: ➖  Removed poetry shell

---

poetry.lock
pyproject.toml

build: :arrow_up: Update dependencies in pyproject.toml

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

This pull request updates the mkdocstrings dependency to version >=0.24.3,<0.26.0 and updates the pre-commit hooks and dependencies.
---
update/change?
---
---

Update mkdocstrings dependency and pre-commit hooks

---

.github/workflows/docker-cd.yml
.github/workflows/python-ci.yml

Formally generated via renovate and add via `cherry-pick`
---
update/change?
---
---

chore: ⬆️ Update dependencies and actions

---

poetry.lock

chore: :arrow_up: Update dependencies

---

.devcontainer/devcontainer.json

chore: :arrow_up: Update devcontainer.json to use dev-3.10 Python image

---

CITATION.cff

feat: :memo: Add the `cff` file for 'doi.org/10.1021/acsomega.3c09262'

---

CITATION.cff
README.md

The README.md file was updated to include a badge displaying the DOI for the software article.
---
update/change?
---
---

fix: :memo: Update citation information and add DOI badge

---

poetry.lock
pyproject.toml

bump: :arrow_up:  Update scikit-learn dependency to v1.5.0

---

CITATION.cff

chore: :pencil2: Update CITATION.cff

---

.github/workflows/weekly-poetry-bot.yml

ci: :green_heart: Update GitHub Actions workflow to include the --fill flag

---

.github/workflows/weekly-poetry-bot.yml

ci: :green_heart: Update GitHub Actions workflow

---

poetry.lock

This is an auto-generated pull request to update dependencies in poetry.lock.

chore(deps): :arrows_counterclockwise: update dependencies 202409011735

---

poetry.lock

This is an auto-generated pull request to update dependencies in poetry.lock.

chore(deps): :arrows_counterclockwise: update dependencies 202409080001

---

poetry.lock

This is an auto-generated pull request to update dependencies in .

chore(deps): :arrows_counterclockwise: update dependencies 202409150001

---

poetry.lock

This is an auto-generated pull request to update dependencies in .

chore(deps): :arrows_counterclockwise: update dependencies 202409220001

---

poetry.lock

This is an auto-generated pull request to update dependencies in <<poetry.lock>>.\n\nUpdated packages:\n\n').

chore(deps): :arrows_counterclockwise: update dependencies 202409290001

---

poetry.lock

This is an auto-generated pull request to update dependencies in `poetry.lock`.\n\nUpdated packages:\n\n

chore(deps): :arrows_counterclockwise: update dependencies 202410060001

---

poetry.lock

This is an auto-generated pull request to update dependencies in `poetry.lock`.\n\nUpdated packages:\n\n

chore(deps): :arrows_counterclockwise: update dependencies 202410130001

---

poetry.lock

This is an auto-generated pull request to update dependencies in `poetry.lock`.\n\nUpdated packages:\n\n

chore(deps): :arrows_counterclockwise: update dependencies 202410200001

---

poetry.lock

This is an auto-generated pull request to update dependencies in `poetry.lock`. Updated packages:

chore(deps): :arrows_counterclockwise: update dependencies 202410270001

---

poetry.lock

This is an auto-generated pull request to update dependencies in `poetry.lock`. Updated packages:

chore(deps): :arrows_counterclockwise: update dependencies 202412150001

---

uv.lock

This is an auto-generated pull request to update dependencies in `uv.lock`.\n\nUpdate Log:\n```\n\n```

chore(deps): :arrows_counterclockwise: update dependencies 202509070013
